version: '3'

services:
  db:
    image: 'postgres:14.3'
    container_name: db
    environment:
      POSTGRES_DB: employeedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432

  jmsbroker:
    image: 'rmohr/activemq:5.15.9'
    container_name: jmsbroker
    ports:
      - 8161:8161
      - 61616:61616

  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - jmsbroker
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/employeedb
      SPRING_ACTIVEMQ_BROKER_URL: tcp://jmsbroker:61616
    ports:
      - 8080:8080

