CREATE TABLE employee (
    employee_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR,
    last_name VARCHAR,
    department_id INT,
    job_title VARCHAR,
    gender VARCHAR,
    date_of_birth DATE
);
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('John', 'Smith', 6, 'PR Manager', 'MALE', '1999-01-05' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Henry', 'Smith', 1, 'TA Specialist', 'MALE', '1998-02-10' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Malcolm', 'Sawyer', 4, 'Artist', 'OTHER', '1997-03-15' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Joe', 'Biden', 2, 'CEO', 'MALE', '1996-04-20' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Joseph', 'Raegan', 5, 'Software Engineer', 'MALE', '1995-05-25' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Steven', 'Willson', 5, 'Software Engineer', 'MALE', '1994-06-02' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Stephen', 'Colbert', 6, 'PR Manager', 'MALE', '1993-07-07' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Robert', 'Bush', 5, 'Software Engineer', 'MALE', '1992-08-12' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Wilhelm', 'Smith', 4, 'Artist', 'MALE', '1991-09-17' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Charles', 'Thegreat', 2, 'COO', 'MALE', '1990-10-22' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Tom', 'Jackson', 4, 'Artist', 'MALE', '1989-11-27' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Josephine', 'Kennedy', 1, 'TA Specialist', 'FEMALE', '1999-12-03' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Mary', 'Smith', 5, 'Software Engineer', 'FEMALE', '1998-01-08' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Angeline', 'Johnson', 5, 'Software Engineer', 'FEMALE', '1997-02-13' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Jacqueline', 'Bouvier', 1, 'Recruiting Specialist', 'FEMALE', '1996-03-18' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Will', 'Samuelson', 6, 'PR Manager', 'MALE', '1995-04-23' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Sam', 'Armstrong', 1, 'Employee Relations', 'MALE', '1994-05-28' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Catherine', 'Bacon', 3, 'Security manager', 'FEMALE', '1993-06-04' );
INSERT INTO employee ( first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Martha', 'Washington', 3, 'Security manager', 'FEMALE', '1992-07-09' );
