apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: jmsbroker
  name: jmsbroker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jmsbroker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: jmsbroker
    spec:
      containers:
        - image: rmohr/activemq:5.15.9
          name: jmsbroker
          ports:
            - containerPort: 8161
            - containerPort: 61616
          resources: {}
      restartPolicy: Always
status: {}
