package com.mastery.java.task.service;
import com.mastery.java.task.dao.EmployeeDao;
import com.mastery.java.task.dto.Employee;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Component
@Scope(value = ConfigurableBeanFactory.SCOPE_SINGLETON)
public class EmployeeService {
    @Autowired
    private EmployeeDao employeeDao;
    public Optional<Employee> getEmployeeByID(Long id){
        try{
            return Optional.of(employeeDao.retrieve(id))    ;
        } catch (EmptyResultDataAccessException e){
            return Optional.empty();
        }

    }
    public List<Employee> getEmployeeByName(String firstName, String lastName){
        return employeeDao.retrieveAll().stream()
                .filter(employee -> (employee.getFirstName().equals(firstName)&&employee.getLastName().equals(lastName)))
                .collect(Collectors.toList());
    }
    public List<Employee> getAllEmployees(){
        return employeeDao.retrieveAll();
    }
    @Transactional
    public Long createEmployeeRecord(Employee employee){
        Long newID=-1L;
        /* Autogenerated ID by database can sometimes throw DublicateKeyException
        (if there were gaps in the id after a delete operation and after filling them
        the sequence cursor is pointing on existing record). We repeat the create() method
        until we get the newID returned. */
        while(newID==-1L){
            try{
                newID = employeeDao.create(employee);
            } catch (DuplicateKeyException e){
                e.printStackTrace();
            }
        }
        return newID;
    }
    public Integer updateEmployeeRecord(Employee employee){
        return employeeDao.update(employee);
    }
    public Integer deleteEmployeeRecord(Long id){
        return employeeDao.delete(id);
    }

}
